CREATE TABLE IF NOT EXISTS account (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username varchar(255) NOT NULL,
    pass    varchar(255) NOT NULL,
    proxy_id BIGINT NOT NULL,
    status_id BIGINT NOT NULL,
    CONSTRAINT proxy_id PRIMARY KEY (id),
    CONSTRAINT UQ_proxy_id UNIQUE (proxy_id)
);


CREATE TABLE IF NOT EXISTS proxy_settings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    short_name varchar(255) NOT NULL,
    login varchar(255) NULL,
    pass varchar(255) NULL,
    ip varchar(255) NOT NULL,
    port integer NOT NULL,
    CONSTRAINT fk_proxy_settings PRIMARY KEY (id)

);
ALTER TABLE account add constraint fk_proxy foreign key (proxy_id) references proxy_settings;

create table if not exists account_status (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    description varchar(255),
    name varchar(255) NOT NULL,
    code integer NOT NULL,
    CONSTRAINT pk_account_status PRIMARY KEY (id)
);

ALTER TABLE account add constraint fk_status foreign key (status_id) references account_status;